name: Deployment Notro Challenge 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Backend
      - name: Install backend dependencies
        run: npm install
      - name: Run backend lint
        run: npm run lint
      - name: Run backend unit tests
        run: npm run test
      - name: Run backend E2E tests
        run: npm run test:e2e

      # Frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend lint
        run: |
          cd frontend
          npm run lint
      - name: Run frontend unit tests
        run: |
          cd frontend
          npm run test -- --watch=false --browsers=ChromeHeadless
