name: CI/CD Notro Challenge 🚀

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  # Job para Backend
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Build backend
        run: |
          cd backend
          npm run build
      - name: Lint backend
        run: |
          cd backend
          npm run lint || true
      - name: Test backend
        run: |
          cd backend
          npm run test -- --watch=false
      - name: E2E backend
        run: |
          cd backend
          npm run test:e2e

  # Job para Frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend unit tests
        run: |
          cd frontend
          npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build frontend
        run: |
          cd frontend
          npm run build -- --configuration production

  # Deploy só acontece se frontend e backend passarem
  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]  # <- depende do sucesso dos dois jobs
    steps:
      - uses: actions/checkout@v3

      # Deploy Frontend no Vercel
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy Frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd frontend
          vercel deploy --prod --yes --token $VERCEL_TOKEN --confirm --name notro-challenge

      # Deploy Backend no Render
      - name: Deploy Backend
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d3ackuodl3ps73emo26g" \
            -H "Authorization: Bearer $RENDER_API_KEY"